# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae84be2878800b29dcf1b8330c4b1f179615a479e55f22250971579efffeaf69649d0354abf2fd5291ddbc154a7d340dcd61ff0554a47beea32f3ef57d8984db

test:
  secret_key_base: 5dd25020953c7dab65ccb49d5beaac962a87b0477b61d6e5e42978557750cd23bd8d09220283cbc86c7b0d6027548a807bbfc6755bd26b6b0ee1d7ca40b1cb03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
